"""API 服务层：为前端 third-web 提供 RESTful API 接口。

用法
----
    uvicorn api:app --host 0.0.0.0 --port 8000 --reload
"""

from __future__ import annotations

import logging
import secrets
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from agents.main_agent import MainAgent

# ---------------------------------------------------------------------------
# 临时诊断日志
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="[DIAG] %(asctime)s %(message)s")
logger = logging.getLogger("api_diagnosis")

# ---------------------------------------------------------------------------
# 项目路径与配置加载
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent
load_dotenv(PROJECT_ROOT / ".env")

CONFIG_PATH = PROJECT_ROOT / "config" / "config.yaml"
DOWNLOAD_REGISTRY: dict[str, Path] = {}


def load_config() -> dict:
    """加载 YAML 配置，失败时返回空 dict。"""
    if not CONFIG_PATH.exists():
        return {}
    try:
        import yaml
    except ImportError:
        return {}
    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        data = yaml.safe_load(file) or {}
    return data if isinstance(data, dict) else {}


# ---------------------------------------------------------------------------
# 请求 / 响应数据模型
# ---------------------------------------------------------------------------


class AgentRunRequest(BaseModel):
    """前端 POST /api/agent/run 请求体。"""
    user_input: str = ""
    state_snapshot: dict[str, Any] = Field(default_factory=dict)


class AgentRunResponse(BaseModel):
    """返回给前端的统一响应结构。"""
    success: bool
    response: dict[str, Any]
    state_snapshot: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# FastAPI 应用实例
# ---------------------------------------------------------------------------

app = FastAPI(
    title="赛智通 Agent API",
    description="为前端 third-web 提供 Agent 调度 RESTful 接口",
    version="1.0.0",
)

# 允许前端跨域请求
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# 路由
# ---------------------------------------------------------------------------


@app.get("/")
def health_check() -> dict[str, str]:
    """健康检查端点，供 Render 等平台探测。"""
    return {"status": "ok", "service": "saizhitong-agent-api"}


@app.get("/api/files/{token}")
def download_generated_file(token: str) -> FileResponse:
    """Download a file generated by MaterialAgent in this server process."""
    path = DOWNLOAD_REGISTRY.get(token)
    if path is None or not path.is_file():
        raise HTTPException(status_code=404, detail="Generated file not found.")
    return FileResponse(path, filename=path.name)


def _register_generated_files(result: dict[str, Any]) -> None:
    response = result.get("response", {})
    raw_files = response.get("files", []) if isinstance(response, dict) else []
    urls: list[str] = []
    for raw_path in raw_files if isinstance(raw_files, list) else []:
        try:
            path = Path(str(raw_path)).resolve()
            path.relative_to(PROJECT_ROOT)
        except (OSError, ValueError):
            continue
        if not path.is_file():
            continue
        token = secrets.token_urlsafe(18)
        DOWNLOAD_REGISTRY[token] = path
        urls.append(f"/api/files/{token}")
    if isinstance(response, dict):
        response["files"] = urls


@app.post("/api/agent/run", response_model=AgentRunResponse)
def run_agent(req: AgentRunRequest) -> AgentRunResponse:
    """Pass one browser turn to MainAgent's conversational entry point."""
    try:
        logger.info(f"  user_input: {repr(req.user_input)}")
        config = load_config()
        agent = MainAgent(config=config)
        result = agent.run_conversation_turn(
            req.user_input,
            req.state_snapshot,
        )
        _register_generated_files(result)
        return AgentRunResponse(**result)

    except Exception as exc:
        logger.exception("MainAgent conversation request failed")
        return AgentRunResponse(
            success=False,
            response={
                "text": f"服务器内部错误：{exc}",
                "type": "error",
                "files": [],
                "recommendations": [],
            },
            state_snapshot=req.state_snapshot,
            metadata={"status": "error", "reset": False},
        )
# ---------------------------------------------------------------------------
# 直接运行时启动开发服务器
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
