"""API 服务层：为前端 third-web 提供 RESTful API 接口。

用法
----
    uvicorn api:app --host 0.0.0.0 --port 8000 --reload
"""

from __future__ import annotations

import logging
import os
import secrets
import hashlib
import json
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from supabase import create_client

from agents.main_agent import MainAgent

# ---------------------------------------------------------------------------
# 临时诊断日志
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="[DIAG] %(asctime)s %(message)s")
logger = logging.getLogger("api_diagnosis")

# ---------------------------------------------------------------------------
# 项目路径与配置加载
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent
load_dotenv(PROJECT_ROOT / ".env")

CONFIG_PATH = PROJECT_ROOT / "config" / "config.yaml"
DOWNLOAD_REGISTRY: dict[str, Path] = {}


def _first_configured_env(*names: str) -> str:
    """Return the first non-empty value from compatible environment names."""
    for name in names:
        value = os.getenv(name, "").strip()
        if value:
            return value
    return ""


def _supabase_api_config() -> tuple[str, str]:
    """Read Supabase API credentials, including names used by the old Vite app."""
    url = _first_configured_env("SUPABASE_URL", "VITE_SUPABASE_URL")
    key = _first_configured_env(
        "SUPABASE_ANON_KEY",
        "VITE_SUPABASE_ANON_KEY",
        "SUPABASE_KEY",
    )
    return url, key


def load_config() -> dict:
    """加载 YAML 配置，失败时返回空 dict。"""
    if not CONFIG_PATH.exists():
        return {}
    try:
        import yaml
    except ImportError:
        return {}
    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        data = yaml.safe_load(file) or {}
    return data if isinstance(data, dict) else {}


# ---------------------------------------------------------------------------
# 请求 / 响应数据模型
# ---------------------------------------------------------------------------


class AgentRunRequest(BaseModel):
    """前端 POST /api/agent/run 请求体。"""
    user_input: str = ""
    state_snapshot: dict[str, Any] = Field(default_factory=dict)


class AgentRunResponse(BaseModel):
    """返回给前端的统一响应结构。"""
    success: bool
    response: dict[str, Any]
    state_snapshot: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


class CompetitionListResponse(BaseModel):
    """Supabase 竞赛列表分页响应。"""
    success: bool = True
    items: list[dict[str, Any]] = Field(default_factory=list)
    total: int = 0
    page: int = 1
    page_size: int = 200
    source: str = "supabase"


class RefreshResponse(BaseModel):
    success: bool
    status: str
    message: str
    job_id: int | None = None
    retry_after_seconds: int | None = None


# ---------------------------------------------------------------------------
# FastAPI 应用实例
# ---------------------------------------------------------------------------

app = FastAPI(
    title="赛智通 Agent API",
    description="为前端 third-web 提供 Agent 调度 RESTful 接口",
    version="1.0.0",
)

# 允许前端跨域请求
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# 路由
# ---------------------------------------------------------------------------


@app.get("/")
def health_check() -> dict[str, str]:
    """健康检查端点，供 Render 等平台探测。"""
    return {"status": "ok", "service": "saizhitong-agent-api"}


@app.get("/api/files/{token}")
def download_generated_file(token: str) -> FileResponse:
    """Download a file generated by MaterialAgent in this server process."""
    path = DOWNLOAD_REGISTRY.get(token)
    if path is None or not path.is_file():
        raise HTTPException(status_code=404, detail="Generated file not found.")
    return FileResponse(path, filename=path.name)


@app.get("/api/competitions", response_model=CompetitionListResponse)
def list_competitions(
    page: int = Query(1, ge=1),
    page_size: int = Query(200, ge=1, le=500),
) -> CompetitionListResponse:
    """Return the live competition rows used by the backend agents."""
    url, key = _supabase_api_config()
    if not url or not key:
        missing = []
        if not url:
            missing.append("SUPABASE_URL")
        if not key:
            missing.append("SUPABASE_ANON_KEY")
        logger.error(
            "Supabase configuration missing: %s. Configure these on the backend service.",
            ", ".join(missing),
        )
        raise HTTPException(
            status_code=503,
            detail=f"Supabase backend configuration is missing: {', '.join(missing)}.",
        )

    start = (page - 1) * page_size
    end = start + page_size - 1
    try:
        result = (
            create_client(url, key)
            .table("competitions")
            .select(
                "id,title,url,source,description,organizer,"
                "regist_end,contest_end,category,level,collected_at,updated_at",
                count="exact",
            )
            .neq("source", "permission_test")
            .order("collected_at", desc=True)
            .range(start, end)
            .execute()
        )
    except Exception as exc:
        logger.exception("Supabase competition query failed")
        raise HTTPException(
            status_code=503,
            detail="Competition database is temporarily unavailable.",
        ) from exc

    return CompetitionListResponse(
        items=result.data or [],
        total=int(result.count or 0),
        page=page,
        page_size=page_size,
    )


def _refresh_store():
    from agents.info_collect.supabase_store import SupabaseStore

    url, anon_key = _supabase_api_config()
    key = _first_configured_env("SUPABASE_SERVICE_ROLE_KEY") or anon_key
    if not url or not key:
        raise HTTPException(status_code=503, detail="Supabase refresh configuration is missing.")
    return SupabaseStore(url=url, key=key)


def _client_ip_hash(request: Request) -> str:
    forwarded = request.headers.get("x-forwarded-for", "")
    address = forwarded.split(",", 1)[0].strip()
    if not address and request.client:
        address = request.client.host
    salt = os.getenv("REFRESH_IP_HASH_SALT", "competition-refresh")
    return hashlib.sha256(f"{salt}:{address}".encode("utf-8")).hexdigest()


def _dispatch_refresh_workflow(job_id: int) -> None:
    token = os.getenv("GITHUB_ACTIONS_TOKEN", "").strip()
    repository = os.getenv(
        "GITHUB_REPOSITORY", "Yhrjkcz1/University-Agent-System"
    ).strip()
    workflow = os.getenv(
        "GITHUB_REFRESH_WORKFLOW", "refresh-competitions.yml"
    ).strip()
    ref = os.getenv("GITHUB_REFRESH_REF", "main").strip()
    if not token:
        raise RuntimeError("GITHUB_ACTIONS_TOKEN is not configured.")

    request = urllib.request.Request(
        f"https://api.github.com/repos/{repository}/actions/workflows/{workflow}/dispatches",
        data=json.dumps({
            "ref": ref,
            "inputs": {"job_id": str(job_id), "trigger_type": "manual"},
        }).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            "User-Agent": "saizhitong-refresh-api",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=20) as response:
        if response.status != 204:
            raise RuntimeError(f"GitHub workflow dispatch returned {response.status}.")


def _refresh_job_is_stale(
    job: dict[str, Any],
    now: datetime | None = None,
) -> bool:
    """Return whether an active refresh job no longer owns the dispatch lock."""
    try:
        started_at = datetime.fromisoformat(str(job.get("started_at")))
        if started_at.tzinfo is None:
            started_at = started_at.replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        return True

    current = now or datetime.now(timezone.utc)
    status = str(job.get("status") or "")
    # queued means GitHub has not acknowledged the dispatch yet.  Do not let
    # an interrupted API request block the button for a full hour.
    timeout = timedelta(minutes=10) if status == "queued" else timedelta(hours=1)
    return current - started_at > timeout


@app.post("/api/competitions/refresh", response_model=RefreshResponse, status_code=202)
def start_competition_refresh(request: Request) -> RefreshResponse:
    store = _refresh_store()
    active = store.get_active_refresh_job()
    if active:
        if _refresh_job_is_stale(active):
            status = str(active.get("status") or "active")
            store.update_refresh_job(
                int(active["id"]),
                status="failed",
                finished_at=datetime.now(timezone.utc).isoformat(),
                error_message=f"Refresh task remained {status} beyond its timeout.",
            )
        else:
            return RefreshResponse(
                success=True,
                status="already_running",
                job_id=int(active["id"]),
                message=(
                    f"刷新任务 #{int(active['id'])} 正在处理中，请稍后查看。"
                ),
            )

    ip_hash = _client_ip_hash(request)
    since = (datetime.now(timezone.utc) - timedelta(minutes=10)).isoformat()
    recent = store.get_recent_ip_refresh(ip_hash, since)
    if recent:
        return RefreshResponse(
            success=False,
            status="rate_limited",
            job_id=int(recent["id"]),
            retry_after_seconds=600,
            message="刷新请求过于频繁，请十分钟后再试。",
        )

    job = store.create_refresh_job("manual", ip_hash, status="queued")
    job_id = int(job["id"])
    try:
        _dispatch_refresh_workflow(job_id)
        store.update_refresh_job(job_id, status="dispatched")
    except Exception as exc:
        store.update_refresh_job(
            job_id,
            status="failed",
            finished_at=datetime.now(timezone.utc).isoformat(),
            error_message=str(exc)[:1000],
        )
        logger.exception("Failed to dispatch refresh workflow")
        raise HTTPException(
            status_code=503,
            detail="无法启动数据库刷新任务，请检查 GitHub Actions 配置。",
        ) from exc

    return RefreshResponse(
        success=True,
        status="accepted",
        job_id=job_id,
        message=(
            f"已提交刷新任务 #{job_id}，请等待几分钟后刷新网站。"
        ),
    )


@app.get("/api/competitions/refresh/status")
def competition_refresh_status() -> dict[str, Any]:
    latest = _refresh_store().get_latest_refresh_job()
    return {"success": True, "job": latest}


def _register_generated_files(result: dict[str, Any]) -> None:
    response = result.get("response", {})
    raw_files = response.get("files", []) if isinstance(response, dict) else []
    urls: list[str] = []
    for raw_path in raw_files if isinstance(raw_files, list) else []:
        try:
            path = Path(str(raw_path)).resolve()
            path.relative_to(PROJECT_ROOT)
        except (OSError, ValueError):
            continue
        if not path.is_file():
            continue
        token = secrets.token_urlsafe(18)
        DOWNLOAD_REGISTRY[token] = path
        urls.append(f"/api/files/{token}")
    if isinstance(response, dict):
        response["files"] = urls


@app.post("/api/agent/run", response_model=AgentRunResponse)
def run_agent(req: AgentRunRequest) -> AgentRunResponse:
    """Pass one browser turn to MainAgent's conversational entry point."""
    try:
        logger.info(f"  user_input: {repr(req.user_input)}")
        config = load_config()
        agent = MainAgent(config=config)
        result = agent.run_conversation_turn(
            req.user_input,
            req.state_snapshot,
        )
        _register_generated_files(result)
        return AgentRunResponse(**result)

    except Exception as exc:
        logger.exception("MainAgent conversation request failed")
        return AgentRunResponse(
            success=False,
            response={
                "text": f"服务器内部错误：{exc}",
                "type": "error",
                "files": [],
                "recommendations": [],
            },
            state_snapshot=req.state_snapshot,
            metadata={"status": "error", "reset": False},
        )
# ---------------------------------------------------------------------------
# 直接运行时启动开发服务器
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
